### ISSUE TITLE
Unknown flag error for k3d cluster create

### ISSUE THREAD

**Issue by lastcoolnameleft** [bartr/fluent-bit-grafana-cloud#1]
# Bug Report

When I run:
`k3d cluster create --config k3d.yaml --k3s-server-arg "--no-deploy=traefik" --k3s-server-arg "--no-deploy=servicelb"`

I get the following error:
`FATA[0000] unknown flag: --k3s-server-arg`
 
## Description

```
# k3d version
k3d version v5.1.0
k3s version v1.21.5-k3s2 (default)
```

## Expected Behavior

No error when running the cluster create command.

**Comment by lastcoolnameleft** [comment]
NOTE: This is running the non-Codespaces version.

**Comment by lastcoolnameleft** [comment]
I tried replacing with `--k3s-arg` but got the following error.  I'd recommend adding a requirements section and listing the expected k3s/k3d versions

```
# k3d cluster create --config k3d.yaml --k3s-arg "--no-deploy=traefik" --k3s-arg "--no-deploy=servicelb"

INFO[0000] Using config file k3d.yaml (k3d.io/v1alpha2#simple)
WARN[0000] Default config apiVersion is 'k3d.io/v1alpha3', but you're using 'k3d.io/v1alpha2': consider migrating.
FATA[0000] K3sExtraArg '--no-deploy=traefik' lacks a node filter, but there's more than one node
```

**Comment by bartr** [comment]
This is a breaking change between k3d 4.x and 5.x. The Codespace still uses 4.8.x because of some upstream dependencies. I'll get a fix merged.

**Comment by bartr** [comment]
- updated the Codespace to use k3d 5.x
- updated k3d.yaml
- updated readme
